---
- name: install apps from roles
  hosts: localhost
  pre_tasks:
  - name: update apt cache
    apt: 
      update_cache: yes
  - name: install less package
    apt:
      install: less
    register: less_status
  - name: install tree package
    apt: 
      install: tree
    register: tree_status
  roles:
  - geerlingguy.nginx
  post_tasks:
  - service:
      name: nginx
      enabled: yes
      state: started
  - debug: 
      msg: both apps status {{ less_status }} {{ tree_status }}