#!/bin/bash

# Define the availability domains ------------ <UPDATE> ----------------
AD1="gtcs:AP-HYDERABAD-1-AD-1"

# Array to hold availability domains
# AVAILABILITY_DOMAINS=("$AD1")

# Loop indefinitely until a command succeeds
while true; do
#    for AVAILABILITY_DOMAIN in "${AVAILABILITY_DOMAINS[@]}"; do
        echo "Attempting to launch instance in Availability Domain: $AD1"
        
 # ----------------------- <UPDATE AS NECESSARY> ------------------------
        oci compute instance launch \
            --availability-domain "$AD1" \
            --compartment-id "ocid1.tenancy.oc1..aaaaaaaasg4p5hw2xxyotpevppxqtnw7cie5ttgbyzq5ay24e77ck4vjrczq" \
            --shape "VM.Standard.A1.Flex" \
            --subnet-id "ocid1.subnet.oc1.ap-hyderabad-1.aaaaaaaau3mnh7h5chpe22jce6yth6fmc3pdxswkjkk6q4lcs573itt5xopa" \
            --assign-private-dns-record true \
            --assign-public-ip true \
            --agent-config '{"is_management_disabled": false, "is_monitoring_disabled": false, "plugins_config": [
                {"desired_state": "DISABLED", "name": "Vulnerability Scanning"},
                {"desired_state": "DISABLED", "name": "Management Agent"},
                {"desired_state": "ENABLED", "name": "Custom Logs Monitoring"},
                {"desired_state": "DISABLED", "name": "Compute RDMA GPU Monitoring"},
                {"desired_state": "ENABLED", "name": "Compute Instance Monitoring"},
                {"desired_state": "DISABLED", "name": "Compute HPC RDMA Auto-Configuration"},
                {"desired_state": "DISABLED", "name": "Compute HPC RDMA Authentication"},
                {"desired_state": "ENABLED", "name": "Cloud Guard Workload Protection"},
                {"desired_state": "DISABLED", "name": "Block Volume Management"},
                {"desired_state": "DISABLED", "name": "Bastion"}]}' \
            --availability-config '{"recovery_action": "RESTORE_INSTANCE"}' \
            --display-name "<PUT_YOUR_VM_NAME>" \
            --image-id "ocid1.image.oc1.ap-hyderabad-1.aaaaaaaa76hls27mlpe5ietuukxidsc5czy3332z5vjoys5nc7gp74fhtena" \
            --instance-options '{"are_legacy_imds_endpoints_disabled": false}' \
            --shape-config '{"memory_in_gbs": 24, "ocpus": 4}' \
            --ssh-authorized-keys-file ./vm/id_rsa.pub

        if [ $? -eq 0 ]; then
            echo "Instance created successfully in $AD1."
            exit 0  # Exit the script after successful execution
        else
            echo "Failed to launch instance in $AD1. Trying the next one..."
            sleep 3  # Wait 3 seconds before trying the next domain
        fi
#    done
done