@host = arunvanam.atlassian.net
@user = arun.vanam@outlook.com
@token = 
@auth = {{user}}:{{token}}
### List projects
GET https://{{host}}/rest/api/3/field
Authorization: Basic {{auth}}
Accept: application/json
Content-Type: application/json

