- hosts: jenkins-master
  become: yes
  tasks:
    - name: Add Jenkins GPG key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present
    # - name: Add Jenkins APT repository
    #   apt_repository:
    #     repo: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
    #     state: present
    #     filename: 'jenkins'
    # - name: repo Add
    #   shell: '''
    #           sudo wget -O /etc/apt/keyrings/jenkins-keyring.asc \
    #           https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    #           echo "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc]" \
    #           https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
    #           /etc/apt/sources.list.d/jenkins.list > /dev/null
    #         '''
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Java (OpenJDK 17)
      apt:
        name: openjdk-17-jre-headless
        state: present
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
    - name: Ensure Jenkins is started and enabled
      systemd:
        name: jenkins
        enabled: yes
        state: started